// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Config struct {
	TermopadsOnPage int     `json:"termopadsOnPage"`
	MaxTemperature  float64 `json:"maxTemperature"`
	MinTemperature  float64 `json:"minTemperature"`
}

type LastPerson struct {
	ID             string  `json:"id"`
	UpdateAt       string  `json:"updateAt"`
	Image          string  `json:"image"`
	Wigand         string  `json:"wigand"`
	WigandFasality string  `json:"wigandFasality"`
	WigandNumber   string  `json:"wigandNumber"`
	Temperature    float64 `json:"temperature"`
	NameFirst      *string `json:"nameFirst"`
	NameMiddle     *string `json:"nameMiddle"`
	NameLast       *string `json:"nameLast"`
	Organization   *string `json:"organization"`
	Departament    *string `json:"departament"`
	Postion        *string `json:"postion"`
}

type Person struct {
	CreatedAt      string  `json:"createdAt"`
	UpdatedAt      string  `json:"updatedAt"`
	Image          string  `json:"image"`
	Wigand         string  `json:"wigand"`
	WigandFasality string  `json:"wigandFasality"`
	WigandNumber   string  `json:"wigandNumber"`
	Temperature    float64 `json:"temperature"`
	NameFirst      *string `json:"nameFirst"`
	NameMiddle     *string `json:"nameMiddle"`
	NameLast       *string `json:"nameLast"`
	Organization   *string `json:"organization"`
	Departament    *string `json:"departament"`
	Postion        *string `json:"postion"`
}

type Temperature struct {
	ID             string  `json:"id"`
	Job            string  `json:"job"`
	Update         string  `json:"update"`
	Temperature    float64 `json:"temperature"`
	Image          *string `json:"image"`
	Wigand         string  `json:"wigand"`
	WigandFasality string  `json:"wigandFasality"`
	WigandNumber   string  `json:"wigandNumber"`
	NameFirst      *string `json:"nameFirst"`
	NameMiddle     *string `json:"nameMiddle"`
	NameLast       *string `json:"nameLast"`
	Organization   *string `json:"organization"`
	Departament    *string `json:"departament"`
	Postion        *string `json:"postion"`
}

type TemperatureLogMetric struct {
	Date           string  `json:"date"`
	Temperature    float64 `json:"temperature"`
	TemperatureMax float64 `json:"temperatureMax"`
	TemperatureMin float64 `json:"temperatureMin"`
	Image          string  `json:"image"`
	PCreateAt      string  `json:"pCreateAt"`
	PUpdateAt      string  `json:"pUpdateAt"`
	PWigand        int     `json:"pWigand"`
	PFirstName     string  `json:"pFirstName"`
	PMiddleName    string  `json:"pMiddleName"`
	PLastName      string  `json:"pLastName"`
	POrganization  string  `json:"pOrganization"`
	PDepartament   string  `json:"pDepartament"`
	PPosition      string  `json:"pPosition"`
	TID            int     `json:"tID"`
	TURL           string  `json:"tURL"`
	TSudosID       int     `json:"tSudosID"`
	TName          string  `json:"tName"`
	TSerial        string  `json:"tSerial"`
	TDescription   string  `json:"tDescription"`
}

type Termopad struct {
	ID             string  `json:"id"`
	SudosID        int     `json:"sudosID"`
	CrateAt        string  `json:"crateAt"`
	Address        string  `json:"address"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	MaxTemperature float64 `json:"maxTemperature"`
	MinTemperature float64 `json:"minTemperature"`
}
